import { Trip } from "./types";

export const FALLBACK_TOURS: Trip[] = [
    {
        _id: "fb-adventure-1",
        title: "Sahara Desert Safari & Star Gazing",
        tripType: "adventure",
        description: "An unforgettable journey into the heart of the Sahara. Experience camel treks, traditional campfires, and the most clear night skies you've ever seen.",
        transportType: "bus",
        transport: "4x4 Luxury Land Cruiser",
        departureCity: "Tunis",
        destination: "Douz",
        duration: 3,
        departureDate: new Date(Date.now() + 86400000 * 7).toISOString(),
        departureOptions: "go_and_back",
        includedServices: ["Accommodation", "All meals", "Guided tours", "Equipment"],
        excludedServices: ["Personal expenses", "Tips"],
        tripHighlights: ["Camel Trek", "Luxury Camping", "Sunset over Dunes", "Local Music"],
        images: ["/assests/slider-banner-1.jpg"],
        price: 850,
        tax: 45,
        maxParticipants: 12,
        travelerType: "any",
        itinerary: [
            {
                day: "Day 1",
                meals: "Lunch, Dinner",
                activities: [
                    { _id: "act-1", activityName: "Arrival in Douz", description: "Welcome tea and orientation" }
                ],
                _id: "it-1",
                accommodation: "Desert Camp"
            }
        ],
        status: "active",
        accommodationDetails: true,
        guideAvailable: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },
    {
        _id: "fb-cultural-1",
        title: "The Roman Heritage: Carthage & El Jem",
        tripType: "cultural",
        description: "Step back in time as you explore the magnificent ruins of Carthage and the world-famous El Jem amphitheatre.",
        transportType: "bus",
        transport: "Premium Touring Coach",
        departureCity: "Tunis",
        destination: "Carthage",
        duration: 1,
        departureDate: new Date(Date.now() + 86400000 * 3).toISOString(),
        departureOptions: "go_and_back",
        includedServices: ["Transportation", "Entry fees", "Professional guide", "Lunch"],
        excludedServices: ["Drinks", "Personal purchases"],
        tripHighlights: ["UNESCO Sites", "Roman Mosaics", "History Experts", "Ancient Ruins"],
        images: ["/assests/hotels.jpg"],
        price: 320,
        tax: 15,
        maxParticipants: 20,
        travelerType: "any",
        itinerary: [],
        status: "active",
        accommodationDetails: false,
        guideAvailable: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },
    {
        _id: "fb-beach-1",
        title: "Djerba Island Premium Escape",
        tripType: "beach",
        description: "Relax on the pristine white sands of Djerba. Enjoy premium spa treatments and exquisite Mediterranean cuisine.",
        transportType: "flight",
        transport: "Domestic Flight + Transfer",
        departureCity: "Tunis",
        destination: "Djerba",
        duration: 5,
        departureDate: new Date(Date.now() + 86400000 * 14).toISOString(),
        departureOptions: "go_and_back",
        includedServices: ["Flights", "5-star Resort", "Breakfast & Dinner", "Airport transfers"],
        excludedServices: ["Spa treatments", "Water sports"],
        tripHighlights: ["Private Beach", "Spa & Wellness", "Local Souks", "Flamingo Island"],
        images: ["/assests/img12.jpg"],
        price: 1250,
        tax: 75,
        maxParticipants: 10,
        travelerType: "any",
        itinerary: [],
        status: "active",
        accommodationDetails: true,
        guideAvailable: false,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    }
];
